# permissions for end users to view saiyams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: saiyam-viewer-role
rules:
- apiGroups:
  - hello.example.com
  resources:
  - saiyams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.example.com
  resources:
  - saiyams/status
  verbs:
  - get
